### ISSUE TITLE
After the latest update It's not working on my end

### ISSUE THREAD

**Issue by rakitanc** [LenAnderson/YouTube-Mouseover-Preview#8]
I am using Chrome
Version 99.0.4844.82 (Official Build) (64-bit)

Also turned off the inline settings

**Comment by LenAnderson** [comment]
Does nothing happen at all, or do you at least get the "Loading Storyboard..." overlay on the video thumbnails?

**Comment by rakitanc** [comment]
Just nothing actually. It was working pretty fine before

**Comment by LenAnderson** [comment]
Interesting. It wasn't working for me anymore, hence the update. Maybe YouTube is testing selective updates again?

Anyways, since YouTube suppresses all JS exceptions, I've pushed another update to the script that should pass on exceptions to the console again.

Please do the following to see if anything from the userscript comes up. Make sure the userscript is updated to version 2.1 first.

1. In Chrome, press `F12` to open the DevTools
2. Switch to the `Console` tab
3. In the `Filter` field enter `[YT-MOP]`
4. Only now navigate to YouTube (or refresh the page if you are already on YouTube).
5. You should see `[YT-MOP] run` in the console
6. Move your mouse over a video thumbnail (not a "short")
7. You should see  
`[YT-MOP] enter ...`  
`[YT-MOP] load storyboard ...`
8. Move your mouse away from the thumbnail and you should see `[YT-MOP] leave ...`

![DevTools](https://i.imgur.com/I5AFYqj.png)

Since the userscript fails on your device, you'll probably see something else, hopefully some exceptions are being logged (should be in red text). Please copy / screenshot those and post them here.

**Comment by igor17721** [comment]
It doesn't work for me either. Version 2.1, microsoft edge. It stopped working today without any reason. Please help

<img width="946" alt="Capture1" src="https://user-images.githubusercontent.com/108469300/176676315-b927b045-707c-44d7-9d67-30d1f968cfc8.PNG">

**Comment by rakitanc** [comment]
![Screenshot from 2022-06-30 21-35-10](https://user-images.githubusercontent.com/64612555/176725297-381de51c-92c7-4ec8-a3da-3f506f0b9d86.png)
This is what i get

**Comment by goooglefc** [comment]
For me it's working but only in incognito mode.

**Comment by LenAnderson** [comment]
Thanks for the console screenshots. Gives me an idea of where to look.

@goooglefc Hmm, that strengthens my suspicion that they currently do some kind of A-B testing, giving some users an updated version of the site.  

Once I get back to civilization I'll have to run some tests with different browsers, incognito / logged out... Probably Tuesday before I can do anything.

**Comment by rakitanc** [comment]
Thanks for the Heads up. Enjoy your holiday

**Comment by LenAnderson** [comment]
Managed to break the script while logged out / incognito. Version 2.2 fixes this as far as I can tell.

If it is still not working for anyone after updating to v2.2 please comment (with console output as described in [previously](https://github.com/LenAnderson/YouTube-Mouseover-Preview/issues/8#issuecomment-1170820333)) and I'll reopen the issue.

**Comment by rakitanc** [comment]
It's working again
